### ISSUE TITLE
Light sensor is always 0

### ISSUE THREAD

**Issue by MikeAndrews90** [CloudConnectKits/Azure_Sphere_SK_ADC_RTApp#1]
Hi,

First of all thanks for putting together these examples! Apologies if this isn't the right place to ask this.

I've just got it running but my light sensor is always reporting as 0.00.

`[Info] Sending telemetry: {"gX":"-0.07", "gY":"0.00", "gZ":"0.00", "aX": "103.58", "aY": "387.35", "aZ": "925.61", "pressure": "1006.00", "light_intensity": "0.00", "altitude": "60.54", "temp": "35.09",  "rssi": "-64"}`

```
LSM6DSO: Acceleration [mg]  : 103.9440, 385.1540, 926.7120
LSM6DSO: Angular rate [dps] : 0.00, 0.00, 0.00
LSM6DSO: Temperature1 [degC]: 35.24
LPS22HH: Pressure     [hPa] : 1005.99
LPS22HH: Temperature2 [degC]: 34.63
ALSPT19: Ambient Light[Lux] : 0.00
```

Any ideas?
Thanks in advance.

**Comment by PeterFenn** [comment]
That Light Sensor value showing zero continuously likely means that you do not have the M4 application running. Run the M4 application, then run the A7 application (from 2nd instance of Visual Studio) and you should see different results.

Please refer to the tutorial procedure that is posted at http://avnet.me/azsphere-tutorial
